### PR TITLE
Week1 - Project initiation 

### PR DESCRIPTION
**Pull request by peterampazzo**

### CODE REVIEW

**Review by Loic-Ker — APPROVED** [review]
Good for me :)

**Review by alessandro-canevaro — COMMENTED** [review]
I'm having a problem creating the conda env.
Im getting this:
`Solving environment: failed

  - ca-certificates==2021.10.26=hecd8cb5_2
  - openssl==1.1.1l=h9ed2024_0
  - setuptools==58.0.4=py38hecd8cb5_0
  - certifi==2021.10.8=py38hecd8cb5_0
  - libcxx==12.0.0=h2f01273_0
  - ncurses==6.3=hca72f7f_2
  - python==3.8.12=h88f2d9e_0
  - readline==8.1=h9ed2024_0
  - xz==5.2.5=h1de35cc_0
  - libffi==3.3=hb1e8313_2
  - sqlite==3.37.0=h707629a_0
  - zlib==1.2.11=h4dc903c_4
  - pip==21.2.4=py38hecd8cb5_0
  - tk==8.6.11=h7bc2e8c_0` 

Am I the only one?

**Comment by peterampazzo** [comment]
@Loic-Ker, @erlahrafnkels do you experience the same error?

**Review by alessandro-canevaro — APPROVED** [review]
now should work with macOS and Win10

**Review by erlahrafnkels — APPROVED** [review]

**Pull request merged**
